var WHITE_PIECES="PNBRQK";
var BLACK_PIECES="pnbrqk";

var RANKS="12345678";
var FILES="abcdefgh";

var WHITE=0;
var BLACK=1;

var SQ_EMPTY=0x0;

var PAWN=0x1;
var KNIGHT=0x2;
var BISHOP=0x3;
var ROOK=0x4;
var QUEEN=0x5;
var KING=0x6;

var WHITE_PAWN=0x1;
var WHITE_KNIGHT=0x2;
var WHITE_BISHOP=0x3;
var WHITE_ROOK=0x4;
var WHITE_QUEEN=0x5;
var WHITE_KING=0x6;

var BLACK_PAWN=0x9;
var BLACK_KNIGHT=0xA;
var BLACK_BISHOP=0xB;
var BLACK_ROOK=0xC;
var BLACK_QUEEN=0xD;
var BLACK_KING=0xE;

var KINGSIDE=0;
var QUEENSIDE=1;

var CASTLING_NONE=0;

var KING_HOME_SQUARE_WHITE=4;
var KING_HOME_SQUARE_BLACK=60;